### ISSUE TITLE
用了您的rwsck脚本

### ISSUE THREAD

**Issue by LeoBoy1st** [randomshit699/Bncr_plugins#2]
青龙执行的时候报错：Error:{'description': 'Method Not Allowed', 'status': 405, 'message': 'Method POST not allowed for URL /api/wsck'}
找不到这个路径，兔子最新的路径应该是什么？

**Comment by randomshit699** [comment]
需要环境变量
export Rabbiturl="http://127.0.0.1:1234/bot/wsck?BotApiToken=xxxxx"
export ServerHost="xxxxxx"
export RabbitToken="xxxxx"
